### ISSUE TITLE
Event publish failed

### ISSUE THREAD

**Issue by oksidisko** [eXsio/php-symfony-arch#3]
Thanks for your work on the demo!

As you mentioned in the article, "we won't have to worry about setting Timeouts, performing Retries and configuring Circuit Breakers", that's why we should choose event based async integration.

But in this scenario we MUST be sure that event is sent (let's not touch consuming part for now). Imagine if in afterTransaction event is not accepted by our MQ broker for some reason (network issue, bad config, server reboot). Some scenarios will be okay, like if we temporary have wrong comments count on a post. But in some cases it will be a major issue: Posts module failed to send Created event, and some user is sending comment, the Comments module Post projection never created, so we will fail here.

It seem like in the current version on the project your solution is baseline events. So we should do this pretty often, or just "be okay" with potentialy outdated data across the system. What would be your solution to keep the system simple enough and avoid "post not found" error, for example.

I hope we don't fall back to good old retries during event producing...

**Comment by eXsio** [comment]
Hi, thanks for this analysis!

We can break it down to 2 scenarios:

A) Event was'nt sent due to a Bug in the Code

The solution would be to fix and deploy, then do a one-time baseline.

B) there's an Infrastructure issue that has prevented the Event from being sent to the Bus.

Infrastructure is usually in a highest availability tier and is expected never to fail to the point of a complete meltdown. We should have sufficient redundancy and failover coverage for that never to happen. That being said, we could log all serialized events in a persistent storage prior to actually sending them out. That Way, If needed, we could "replay" them via simple code logic. This approach would be similar to Event Sourcing.

**Comment by parijke** [comment]
Isn't that what the Symfony Messenger is designed for? Or maybe I missed the essence of the question.

**Comment by eXsio** [comment]
I think all's clear. Closing.
